language: node_js
node_js:
 - 6.9.5
services: mongodb
before_install:
  - sleep 15
  - mongo GimnasioAPP  --eval 'db.createUser({user:"gpsAdmin",pwd:"Gps@1718",roles:["readWrite"]});'
install:
  - cd ./gimnasio-server
  - npm install -g istanbul mocha
  - npm install
script:
  - nyc cover _mocha
  - codecov